include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = AmbrosiaDock

AmbrosiaDock_OBJC_FILES = \
	main.m \
	AppDelegate.m \
	DockController.m \
	DockView.m \
	DockItem.m \
	ForceQuitController.m

AmbrosiaDock_OBJCFLAGS  = -fobjc-arc
AmbrosiaDock_LDFLAGS    =

AmbrosiaDock_PRINCIPAL_CLASS = AppDelegate

AmbrosiaDock_RESOURCE_FILES = Resources/DefaultDock.plist

include $(GNUSTEP_MAKEFILES)/application.make
