RPM_DISABLE_RELOCATABLE=YES

include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECTS = \
	Ambrosia \
	Audio \
	Bluetooth \
	Video \
	Network \
	Power \

-include GNUmakefile.preamble

-include GNUmakefile.local

include $(GNUSTEP_MAKEFILES)/aggregate.make

-include GNUmakefile.postamble

