include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = MenuServer

MenuServer_OBJC_FILES = \
	main.m \
	AppDelegate.m \
	MenuBarController.m \
	MenuBarView.m \
	BluetoothStatusItem.m \
	WiFiStatusItem.m \
	VolumeStatusItem.m

MenuServer_OBJCFLAGS  = -fobjc-arc
MenuServer_LDFLAGS    =

MenuServer_PRINCIPAL_CLASS = AppDelegate

include $(GNUSTEP_MAKEFILES)/application.make
